x-default-logging: &logging
  driver: json-file
  options:
    max-size: 5m
    max-file: "2"
    tag: "{{.Name}}"

x-default-node-exporter-config: &node-exporter-config
  image: prom/node-exporter:latest
  deploy:
    resources:
      limits:
        memory: 50M
  ports:
    - "9100"
  restart: unless-stopped
  logging: *logging

services:
  alloy-1:
    image: grafana/alloy:latest
    container_name: alloy-1
    hostname: alloy-1
    deploy:
      resources:
        limits:
          memory: 200M
    restart: unless-stopped
    command: [
      "run",
      "--server.http.listen-addr=0.0.0.0:12345",
      "--storage.path=/var/lib/alloy/data",
      "--stability.level=experimental",
      "--cluster.enabled",
      "--cluster.join-addresses=alloy-1,alloy-2",
      "--cluster.name=alloy-cluster",
      "/etc/alloy/config.alloy"
    ]
    user: 0:0
    volumes:
      - ./config.alloy:/etc/alloy/config.alloy
    ports:
      - "12345:12345"
      - "4317"
    healthcheck:
      test: >
        bash -c 'exec 3<>/dev/tcp/localhost/12345 &&
                 printf "GET /-/ready HTTP/1.1\r\nHost: localhost\r\nConnection: close\r\n\r\n" >&3 &&
                 cat <&3 | grep -q "Alloy is ready"'
      start_period: 10s
      interval: 2s
      timeout: 1s
      retries: 10
    logging: *logging

  alloy-2:
    image: grafana/alloy:latest
    container_name: alloy-2
    hostname: alloy-2
    deploy:
      resources:
        limits:
          memory: 200M
    restart: unless-stopped
    command: [
      "run",
      "--server.http.listen-addr=0.0.0.0:12345",
      "--storage.path=/var/lib/alloy/data",
      "--stability.level=experimental",
      "--cluster.enabled",
      "--cluster.join-addresses=alloy-1,alloy-2",
      "--cluster.name=alloy-cluster",
      "/etc/alloy/config.alloy"
    ]
    user: 0:0
    volumes:
      - ./config.alloy:/etc/alloy/config.alloy
    ports:
      - "12346:12345"
      - "4317"
    healthcheck:
      test: >
        bash -c 'exec 3<>/dev/tcp/localhost/12345 &&
                 printf "GET /-/ready HTTP/1.1\r\nHost: localhost\r\nConnection: close\r\n\r\n" >&3 &&
                 cat <&3 | grep -q "Alloy is ready"'
      start_period: 10s
      interval: 2s
      timeout: 1s
      retries: 10
    # Helpful for smooth cluster creation
    depends_on:
      alloy-1:
        condition: service_healthy
    logging: *logging
  
  node-exporter-1:
    container_name: node-exporter-1
    image: prom/node-exporter:latest
    <<: *node-exporter-config

  node-exporter-2:
    container_name: node-exporter-2
    <<: *node-exporter-config

  node-exporter-3:
    container_name: node-exporter-3
    <<: *node-exporter-config

  node-exporter-4:
    container_name: node-exporter-4
    <<: *node-exporter-config

  node-exporter-5:
    container_name: node-exporter-5
    image: prom/node-exporter:latest
    <<: *node-exporter-config

  node-exporter-6:
    container_name: node-exporter-6
    <<: *node-exporter-config

  node-exporter-7:
    container_name: node-exporter-7
    <<: *node-exporter-config

  node-exporter-8:
    container_name: node-exporter-8
    <<: *node-exporter-config
