x-default-logging: &logging
  driver: json-file
  options:
    max-size: 5m
    max-file: "2"
    tag: "{{.Name}}"

x-default-otel-generator-config: &generator-config
  image: ghcr.io/krzko/otelgen:latest
  deploy:
    resources:
      limits:
        memory: 50M
  restart: unless-stopped
  logging: *logging

services:
  alloy:
    image: grafana/alloy:latest
    container_name: alloy
    deploy:
      resources:
        limits:
          memory: 200M
    restart: unless-stopped
    command: ["run", "--server.http.listen-addr=0.0.0.0:12345", "--storage.path=/var/lib/alloy/data", "--stability.level=experimental", "/etc/alloy/config.alloy"]
    user: 0:0
    volumes:
      - ./config.alloy:/etc/alloy/config.alloy
    ports:
      - "12345:12345"
      - "4317"
    logging: *logging
  
  otel-metrics-generator:
    container_name: otel-metrics-generator
    <<: *generator-config
    command: ["--insecure", "--service-name=otel-metrics", "--rate=1", "--otel-exporter-otlp-endpoint=alloy:4317", "metrics", "gauge"]

  otel-logs-generator:
    container_name: otel-logs-generator
    <<: *generator-config
    command: ["--insecure", "--service-name=otel-logs", "--rate=1", "--otel-exporter-otlp-endpoint=alloy:4317", "logs", "multi"]

  otel-traces-generator:
    container_name: otel-traces-generator
    <<: *generator-config
    command: ["--insecure", "--duration=86400", "--rate=1", "--service-name=otel-traces", "--otel-exporter-otlp-endpoint=alloy:4317", "traces", "multi"]
